import React, { useState, useEffect } from 'react';
import { ProjectIdea, StudentProfile, RealityCheckReport, ProjectBlueprint } from '../../types';
import { geminiService } from '../../services/gemini';
import {
  FileCode2,
  Download,
  Copy,
  Check,
  Sparkles,
  Layers,
  Database,
  Shield,
  Milestone,
  Cpu,
  Server,
  Cloud,
  ArrowRight,
  Code,
  Lock,
  Terminal,
} from 'lucide-react';

interface BlueprintViewProps {
  idea: ProjectIdea | null;
  profile: StudentProfile;
  realityCheck?: RealityCheckReport | null;
  existingBlueprint?: ProjectBlueprint | null;
  onSaveBlueprint: (blueprint: ProjectBlueprint) => void;
  onNavigateToRoadmap: () => void;
  onBackToGenerator: () => void;
}

export const BlueprintView: React.FC<BlueprintViewProps> = ({
  idea,
  profile,
  realityCheck,
  existingBlueprint,
  onSaveBlueprint,
  onNavigateToRoadmap,
  onBackToGenerator,
}) => {
  const [blueprint, setBlueprint] = useState<ProjectBlueprint | null>(existingBlueprint || null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'overview' | 'architecture' | 'tech' | 'database' | 'security' | 'viva'>('overview');
  const [copied, setCopied] = useState(false);

  const fetchBlueprint = async () => {
    if (!idea) return;
    setLoading(true);
    setError(null);
    try {
      const result = await geminiService.generateBlueprint(idea, profile, realityCheck || undefined);
      setBlueprint(result.blueprint);
      onSaveBlueprint(result.blueprint);
    } catch (err: any) {
      console.error('Blueprint generation failure:', err);
      setError(err.message || 'Failed to generate project blueprint.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (idea && !blueprint) {
      fetchBlueprint();
    }
  }, [idea?.id]);

  if (!idea) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center text-slate-100">
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 max-w-md mx-auto">
          <FileCode2 className="w-12 h-12 text-slate-500 mx-auto mb-4" />
          <h2 className="text-lg font-bold text-white mb-2">No Project Selected</h2>
          <p className="text-xs text-slate-400 mb-6">
            Please choose a project idea to generate its 18-section architectural blueprint.
          </p>
          <button
            onClick={onBackToGenerator}
            className="px-5 py-2.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs"
          >
            Go to Project Generator
          </button>
        </div>
      </div>
    );
  }

  // Export to Markdown
  const handleExportMarkdown = () => {
    if (!blueprint) return;
    const md = `# Project Blueprint: ${idea.title}
**Domain:** ${idea.domain} | **Difficulty:** ${idea.difficulty} | **Estimated Effort:** ${idea.estimatedTime}
Generated by ProjectForge AI Engineering Platform

## 1. Project Overview
${blueprint.projectOverview}

## 2. Problem Statement
${blueprint.problem}

## 3. Target Users
${blueprint.targetUsers.map((u) => `- ${u}`).join('\n')}

## 4. Proposed Solution
${blueprint.proposedSolution}

## 5. Unique Value
${blueprint.uniqueValue}

## 6. Core Features
${blueprint.coreFeatures.map((f) => `- ${f}`).join('\n')}

## 7. Optional & Stretch Features
${blueprint.optionalFeatures.map((f) => `- ${f}`).join('\n')}

## 8. Recommended Technology Stack (WHAT / WHY / HOW)
${blueprint.recommendedTechStack.map((t) => `### ${t.name} (${t.category})\n- **WHAT:** ${t.purpose}\n- **WHY:** ${t.why}\n- **HOW:** ${t.how}`).join('\n\n')}

## 9. System Architecture Overview
${blueprint.architectureOverview}

## 10. Database Schema (Cloud Firestore)
${blueprint.databaseDesign.collections.map((c) => `### Collection: \`${c.name}\`\n**Purpose:** ${c.purpose}\n**Sample Fields:** ${c.sampleFields.join(', ')}`).join('\n\n')}

## 11. API / Backend Endpoints
${blueprint.apiBackendRequirements.map((e) => `- \`${e.method} ${e.endpoint}\`: ${e.purpose} (Security: ${e.security})`).join('\n')}

## 12. AI Components
${blueprint.aiComponents.map((a) => `- **Model:** ${a.service} | **Role:** ${a.role} | **Strategy:** ${a.promptStrategy}`).join('\n')}

## 13. Security Considerations
${blueprint.securityConsiderations.map((s) => `- ${s}`).join('\n')}

## 14. Testing Strategy
- **Unit Tests:** ${blueprint.testingStrategy.unitTests.join('; ')}
- **Integration Tests:** ${blueprint.testingStrategy.integrationTests.join('; ')}
- **Security Tests:** ${blueprint.testingStrategy.securityTests.join('; ')}

## 15. Deployment Strategy
- **Hosting:** ${blueprint.deploymentStrategy.hosting}
- **CI/CD:** ${blueprint.deploymentStrategy.cicd}
- **Monitoring:** ${blueprint.deploymentStrategy.monitoring}

## 16. Potential Challenges & Mitigations
${blueprint.potentialChallenges.map((c) => `- ${c}`).join('\n')}

## 17. Future Improvements
${blueprint.futureImprovements.map((f) => `- ${f}`).join('\n')}
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${idea.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-blueprint.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyJson = () => {
    if (!blueprint) return;
    navigator.clipboard.writeText(JSON.stringify(blueprint, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:px-8 text-slate-100">
      {/* Header Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 mb-6">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-400 uppercase tracking-wider mb-2">
              <FileCode2 className="w-4 h-4" />
              <span>Comprehensive 18-Section Technical Blueprint</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">{idea.title}</h1>
            <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-2xl">{idea.shortDescription}</p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              id="btn-export-blueprint-md"
              onClick={handleExportMarkdown}
              disabled={!blueprint || loading}
              className="px-3.5 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"
              title="Download formatted Markdown for College Thesis / Project Report"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .MD</span>
            </button>

            <button
              id="btn-copy-blueprint-json"
              onClick={handleCopyJson}
              disabled={!blueprint || loading}
              className="px-3.5 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied JSON' : 'Copy JSON'}</span>
            </button>

            <button
              id="btn-blueprint-to-roadmap"
              onClick={onNavigateToRoadmap}
              className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold shadow-md shadow-blue-600/20 flex items-center space-x-1.5 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"
            >
              <Milestone className="w-3.5 h-3.5" />
              <span>Interactive Roadmap</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Navigation Tabs for 18 sections */}
        <div className="flex flex-wrap gap-2 mt-6 pt-6 border-t border-slate-800">
          {[
            { id: 'overview', label: '1. Overview & Scope' },
            { id: 'architecture', label: '2. Architecture & Data Flow' },
            { id: 'tech', label: '3. Tech Stack (WHAT/WHY/HOW)' },
            { id: 'database', label: '4. Database & APIs' },
            { id: 'security', label: '5. Security & Testing' },
            { id: 'viva', label: '6. Deployment & Viva Defense' },
          ].map((tab) => (
            <button
              key={tab.id}
              id={`tab-blueprint-${tab.id}`}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                activeTab === tab.id
                  ? 'bg-blue-600 text-white shadow-sm font-semibold'
                  : 'bg-slate-800/80 text-slate-400 hover:text-white hover:bg-slate-800'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Loading Skeleton */}
      {loading && (
        <div className="text-center py-20 bg-slate-900/60 border border-slate-800 rounded-2xl">
          <Sparkles className="w-10 h-10 text-blue-400 animate-spin mx-auto mb-4" />
          <h3 className="text-base font-bold text-white mb-2">Generating 18-Section Technical Blueprint...</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto">
            Structuring architecture diagrams, database schema collections, security considerations, and testing rubrics.
          </p>
        </div>
      )}

      {/* Blueprint Content */}
      {!loading && blueprint && (
        <div className="space-y-6">
          {/* TAB 1: Overview & Scope */}
          {activeTab === 'overview' && (
            <div className="space-y-6">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-3">1. Executive Overview</h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">{blueprint.projectOverview}</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-blue-400 uppercase tracking-wider mb-2">2. Problem Statement</h3>
                  <p className="text-xs text-slate-300 leading-relaxed mb-4">{blueprint.problem}</p>
                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">3. Target Audience</h4>
                  <div className="flex flex-wrap gap-1.5">
                    {blueprint.targetUsers.map((u, i) => (
                      <span key={i} className="text-xs px-2.5 py-1 rounded bg-slate-800 border border-slate-700 text-slate-300">
                        {u}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-emerald-400 uppercase tracking-wider mb-2">4. Proposed Solution</h3>
                  <p className="text-xs text-slate-300 leading-relaxed mb-4">{blueprint.proposedSolution}</p>
                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">5. Unique Value Proposition</h4>
                  <p className="text-xs text-slate-300 leading-relaxed bg-slate-950 p-3 rounded-lg border border-slate-800">
                    {blueprint.uniqueValue}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-3">6. Core Features</h3>
                  <ul className="space-y-2 text-xs text-slate-300">
                    {blueprint.coreFeatures.map((feat, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-cyan-400 font-bold">•</span>
                        <span>{feat}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-purple-400 uppercase tracking-wider mb-3">7. Optional & Stretch Goals</h3>
                  <ul className="space-y-2 text-xs text-slate-300">
                    {blueprint.optionalFeatures.map((feat, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-purple-400 font-bold">•</span>
                        <span>{feat}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: Architecture & Data Flow */}
          {activeTab === 'architecture' && (
            <div className="space-y-6">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-2">8. Architecture Overview</h3>
                <p className="text-xs text-slate-300 leading-relaxed mb-6">{blueprint.architectureOverview}</p>

                {/* Layered Representation */}
                <h4 className="text-xs font-bold text-blue-400 uppercase tracking-wider mb-3">System Architecture Tiers</h4>
                <div className="space-y-3 font-mono text-xs">
                  {blueprint.architectureNodes.map((node, idx) => (
                    <div key={idx} className="p-3.5 rounded-lg bg-slate-950 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <div className="flex items-center space-x-3">
                        <span className="w-6 h-6 rounded bg-blue-900/60 text-blue-300 flex items-center justify-center font-bold text-[11px] flex-shrink-0">
                          {idx + 1}
                        </span>
                        <div>
                          <span className="text-xs font-bold text-white">{node.component}</span>
                          <span className="text-slate-500 text-[11px] block">{node.layer}</span>
                        </div>
                      </div>
                      <div className="text-right sm:max-w-md">
                        <span className="text-cyan-400 font-medium text-xs">{node.technology}</span>
                        <p className="text-[11px] text-slate-400 font-sans mt-0.5">{node.role}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: Tech Stack (WHAT / WHY / HOW) */}
          {activeTab === 'tech' && (
            <div className="space-y-6">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-2">
                  9. Recommended Technology Stack
                </h3>
                <p className="text-xs text-slate-400 mb-6">
                  Every technology is justified with WHAT, WHY, and HOW so you can answer academic viva questions with precision.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {blueprint.recommendedTechStack.map((tech, idx) => (
                    <div key={idx} className="p-4 rounded-xl bg-slate-950 border border-slate-800/90 text-xs">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className="font-bold text-sm text-white">{tech.name}</span>
                          {tech.isGoogleService && (
                            <span className="text-[10px] bg-blue-950 text-blue-300 font-semibold px-2 py-0.5 rounded border border-blue-700/60">
                              ★ Google Service
                            </span>
                          )}
                        </div>
                        <span className="text-[10px] text-slate-400 font-mono bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                          {tech.category}
                        </span>
                      </div>

                      <div className="space-y-2 mt-3 text-slate-300">
                        <div className="bg-slate-900/80 p-2 rounded">
                          <span className="text-emerald-400 font-bold block text-[11px]">WHAT (Role):</span>
                          <span className="text-[11px] leading-relaxed">{tech.purpose}</span>
                        </div>
                        <div className="bg-slate-900/80 p-2 rounded">
                          <span className="text-blue-400 font-bold block text-[11px]">WHY (Suitability):</span>
                          <span className="text-[11px] leading-relaxed">{tech.why}</span>
                        </div>
                        <div className="bg-slate-900/80 p-2 rounded">
                          <span className="text-amber-400 font-bold block text-[11px]">HOW (Implementation):</span>
                          <span className="text-[11px] leading-relaxed">{tech.how}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: Database & APIs */}
          {activeTab === 'database' && (
            <div className="space-y-6">
              {/* Database Design */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-2 flex items-center gap-2">
                  <Database className="w-4 h-4 text-amber-400" />
                  <span>10. Cloud Firestore Database Schema</span>
                </h3>
                <p className="text-xs text-slate-400 mb-6">{blueprint.databaseDesign.description}</p>

                <div className="space-y-4">
                  {blueprint.databaseDesign.collections.map((col, idx) => (
                    <div key={idx} className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs">
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-mono text-xs font-bold text-amber-300">{col.name}</span>
                        <span className="text-[10px] text-slate-500 uppercase font-semibold">Document Collection</span>
                      </div>
                      <p className="text-xs text-slate-300 mb-3">{col.purpose}</p>
                      <div className="flex flex-wrap gap-1.5">
                        <span className="text-[11px] text-slate-500 mr-1">Fields:</span>
                        {col.sampleFields.map((field, fIdx) => (
                          <span key={fIdx} className="font-mono text-[11px] px-2 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-800">
                            {field}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* API Endpoints */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Server className="w-4 h-4 text-cyan-400" />
                  <span>11. API / Server-Side Route Specifications</span>
                </h3>

                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="border-b border-slate-800 text-slate-400">
                        <th className="pb-2 font-semibold">Method</th>
                        <th className="pb-2 font-semibold">Endpoint</th>
                        <th className="pb-2 font-semibold">Purpose</th>
                        <th className="pb-2 font-semibold">Security Requirement</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60 font-mono">
                      {blueprint.apiBackendRequirements.map((req, idx) => (
                        <tr key={idx} className="hover:bg-slate-800/30">
                          <td className="py-2.5">
                            <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                              req.method === 'GET' ? 'bg-blue-950 text-blue-400' : 'bg-emerald-950 text-emerald-400'
                            }`}>
                              {req.method}
                            </span>
                          </td>
                          <td className="py-2.5 text-cyan-300">{req.endpoint}</td>
                          <td className="py-2.5 font-sans text-slate-300">{req.purpose}</td>
                          <td className="py-2.5 font-sans text-slate-400 text-[11px]">{req.security}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* AI Components */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-blue-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />
                  <span>12. AI & Machine Learning Integration</span>
                </h3>
                <div className="space-y-3">
                  {blueprint.aiComponents.map((ai, idx) => (
                    <div key={idx} className="p-3.5 rounded-lg bg-slate-950 border border-slate-800 text-xs">
                      <div className="font-bold text-white mb-1">{ai.service}</div>
                      <p className="text-slate-300 mb-2">{ai.role}</p>
                      <span className="text-[11px] text-slate-400 block font-mono">
                        Prompt Strategy: {ai.promptStrategy}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 5: Security & Testing */}
          {activeTab === 'security' && (
            <div className="space-y-6">
              {/* Security Considerations */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-rose-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Lock className="w-4 h-4" />
                  <span>13. Security Considerations & Protections</span>
                </h3>
                <ul className="space-y-3 text-xs text-slate-300">
                  {blueprint.securityConsiderations.map((sec, idx) => (
                    <li key={idx} className="flex items-start gap-2.5 bg-slate-950 p-3 rounded-lg border border-slate-800/80">
                      <Shield className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
                      <span className="leading-relaxed">{sec}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Testing Strategy */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-emerald-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Shield className="w-4 h-4" />
                  <span>14. Rigorous Multi-Tier Testing Strategy</span>
                </h3>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
                    <h4 className="font-bold text-white mb-2">Unit Tests</h4>
                    <ul className="space-y-1.5 text-slate-400">
                      {blueprint.testingStrategy.unitTests.map((t, i) => (
                        <li key={i}>• {t}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
                    <h4 className="font-bold text-white mb-2">Integration Tests</h4>
                    <ul className="space-y-1.5 text-slate-400">
                      {blueprint.testingStrategy.integrationTests.map((t, i) => (
                        <li key={i}>• {t}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
                    <h4 className="font-bold text-white mb-2">Security Tests</h4>
                    <ul className="space-y-1.5 text-slate-400">
                      {blueprint.testingStrategy.securityTests.map((t, i) => (
                        <li key={i}>• {t}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 6: Deployment & Viva Defense */}
          {activeTab === 'viva' && (
            <div className="space-y-6">
              {/* Deployment Strategy */}
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Cloud className="w-4 h-4" />
                  <span>15. Deployment & Production Pipeline</span>
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
                  <div className="p-3.5 rounded-lg bg-slate-950 border border-slate-800">
                    <span className="font-bold text-white block mb-1">Target Hosting</span>
                    <span className="text-slate-400">{blueprint.deploymentStrategy.hosting}</span>
                  </div>
                  <div className="p-3.5 rounded-lg bg-slate-950 border border-slate-800">
                    <span className="font-bold text-white block mb-1">CI/CD Pipeline</span>
                    <span className="text-slate-400">{blueprint.deploymentStrategy.cicd}</span>
                  </div>
                  <div className="p-3.5 rounded-lg bg-slate-950 border border-slate-800">
                    <span className="font-bold text-white block mb-1">Production Telemetry</span>
                    <span className="text-slate-400">{blueprint.deploymentStrategy.monitoring}</span>
                  </div>
                </div>
              </div>

              {/* Viva Challenges & Future Improvements */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-amber-400 uppercase tracking-wider mb-3">
                    16. Potential Challenges & Exam Answers
                  </h3>
                  <ul className="space-y-2 text-xs text-slate-300">
                    {blueprint.potentialChallenges.map((c, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-amber-400 font-bold">•</span>
                        <span>{c}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-emerald-400 uppercase tracking-wider mb-3">
                    17. Future Improvements (Post-Viva Roadmap)
                  </h3>
                  <ul className="space-y-2 text-xs text-slate-300">
                    {blueprint.futureImprovements.map((f, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-emerald-400 font-bold">•</span>
                        <span>{f}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
